version: "3.8"

services:
  my-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
       MYSQL_DATABASE: 'lms'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306 
    healthcheck:
      test: "exit 0"
  app:
    depends_on:
        my-db:
            condition: service_healthy
 
    build: . 
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://my-db:3306/lms?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
