version: '3'
services:
  my-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'lms'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '9090:9090'
    expose:
      # Opens port 3306 on the container
      - '9090'
    healthcheck:
      test: "exit 0"
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8101:8101'
    links:
      - db
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://my-db:9090/lms?autoReconnect=true&useSSL=false
